# Classification:-

We know classification is a technique present in Supervised learning.We use classification where you Y column/label/output column has more than 2 outputs.So we already know there is mainly four types of classifiers we can use for classification.Those are:
    
    1> Naive bayes classifier
    
    2> KNearest Neighbors Classifier(KNN)
    
    3> Decision Tree
    
    4> Support Vector Machine(SVM)
    


#    For Naive bayes classifier we already know everything.We cover this topic on 20th august class.In this class we only focuse on KNearest Neighbors Classifier(KNN), Decision Tree, Support Vector Machine(SVM)

# 2> KNearest Neighbors Classifier(KNN):-

KNN algorithm used for both classification and regression problems.KNN has the following basic steps:

    1. Calculate distance

    2. Find closest neighbors

    3. Vote for labels


# Now I will load the iris dataset and perform KNN , Decision Tree and Support Vector Machine(SVM) to check what kind of accuracy they will provide:

In [54]:
import pandas as pd
import numpy as np
import sklearn
#Calling KNeighborsClassifier class
from sklearn.neighbors import KNeighborsClassifier
#Calling DecisionTreeClassfier class
from sklearn.tree import DecisionTreeClassifier
#Calling SVC class
from sklearn.svm import SVC

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings("ignore")

from sklearn.datasets import load_iris

In [5]:
irisds=load_iris()
irisds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
irisds.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
irisds.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
irisds.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
irisds.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
df=pd.DataFrame(data=irisds.data,columns=irisds.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
df["Target"]=irisds.target
df.head(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   

   Target  
0       0  
1       0

# Spliting the data for input(x) and output(y) variable:

In [13]:
x=df.iloc[:,:-1]
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [14]:
y=df.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Target, Length: 150, dtype: int32

# Split data for machine learning using train_test_split:

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=42)

# Calling KNeighborsClassifier:

In [24]:
knn=KNeighborsClassifier()

# Feed data to machine for training porpose using fit() method:

In [25]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

# Testing machine using predict() function:

In [26]:
pred=knn.predict(x_test)
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

# Checking accuracy_score,confusion_matrix,classification_report:

In [27]:
print(accuracy_score(y_test,pred))

1.0


In [28]:
print(confusion_matrix(y_test,pred))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [30]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



# Here you can see my accuracy score is 1.0 means 100% now imagine that somehow you get 90% or above score that is good but if your accuracy score is like 80% so you have to improve your score so here is a technique:
    If you remember I use an instance named knn to call KNeighborsClassifier() class.In KNeighborsClassifier() paranthesis there is default 5 is present this 5 is KNN value you have to increase it but remember always chose odd number like 7,9,11.Here is an example how can you use it:

In [33]:
knn_new=KNeighborsClassifier(9)

In [34]:
knn_new.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [35]:
pred_new=knn_new.predict(x_test)
pred_new

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [36]:
print(accuracy_score(y_test,pred_new))

1.0


Lets have a look I change KNeighborsClassifier(9) 5 to 9 but still its give 100% accuracy.So whenever you get low accuracy you can increase knn value to odd one ans try to increase your accuracy score.

# DecisionTreeClassfier:

# Now I will perform Decision Tree classifier with iris dataset to check how much accuracy I will get.I will use same x and y data that I created earlier to train and test machine.Lets see:

# Performing Decision Tree classfier in iris dataset:

first I have to import DecisionTreeClassfier from sklearn.tree. I used this code at earlier starting of this page where I call every library pleace check.

# Calling DecisionTreeClassifier:

In [38]:
#Creating an instance named dtc and calling DecisionTreeClassifier with the help of it
dtc=DecisionTreeClassifier()

# Feed data to machine for training porpose using fit() method:

In [39]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

# Testing machine using predict() function:

In [40]:
prediction=dtc.predict(x_test)
prediction

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

# Checking accuracy_score,confusion_matrix,classification_report for Decision Tree classifier:

In [41]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [42]:
print(confusion_matrix(y_test,prediction))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [43]:
print(accuracy_score(y_test,prediction))

1.0


# Here you can see while using Decision Tree classifier in iris dataset I get 1.0 accuracy means 100% accuracy but if you get lower accuracy like 80% how you can increase the accuracy? So there is a parameter called criterion, that is present in DecisionTreeClassifier() paranthesis.By default criterion=”gini” so you can change it with  “entropy” or “log_loss”  to get different accuracy.Let see how I can use it:

In [48]:
#criterion="gini" is default
dtcen=DecisionTreeClassifier(criterion="entropy")

In [49]:
dtcen.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [51]:
preden=dtcen.predict(x_test)
preden

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [53]:
print(accuracy_score(y_test,preden))

0.9777777777777777


Here you can see while I change criterion value "gini"(Which is default) to "entropy" so accuracy got decress 100% to 97%.So now you can change criterion parameter to “log_loss” to check the accuracy score by yourself.

# So here is the final point if you face low accuracy issue while using DecisionTreeClassifier you have to change default parameter criterion='gini' to "entropy" or "log_loss" to check the accuracy.

# Support Vector Machine(SVM):

# Now I will perform SVC that means support vector classifier with iris dataset to check how much accuracy I will get.I will use same x and y data that I created earlier to train and test machine.Lets see:

# Performing SVC in iris dataset:

First I have to import SVC from sklearn.svm. I used this code at earlier starting of this page where I call every library pleace check.

# Calling SVC:

In [55]:
#Calling SVC class using svc because python is case sencitive so I can use lower case letter
svc=SVC()


# Feed data to machine for training porpose using fit() method:

In [56]:
svc.fit(x_train,y_train)

SVC()

# Testing machine using predict() function:

In [58]:
pre=svc.predict(x_test)
pre

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

# Checking accuracy_score:

In [59]:
print(accuracy_score(y_test,pre))

1.0


# So here you can see using SVC in iris dataset is also give me 100% accuracy.But if you get low accuracy like 80% how you can increase the accuracy? So there is a parameter called kernel, that is present in SVC() paranthesis.By default kernel="rbf" so you can change it with "linear","poly","sigmoid" or "precomputed"to get different accuracy.Let see how I can use it:

In [60]:
svc_new=SVC(kernel="poly")

In [62]:
svc_new.fit(x_train,y_train)

SVC(kernel='poly')

In [63]:
pred=svc_new.predict(x_test)
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [64]:
accuracy_score(y_test,pred)

0.9777777777777777

# So you can see while I change parameter named kernel "rbf"(Which is default) to "poly" my accuracy score is decrease so if you can change the kernel parameter to "linear","sigmoid"or "precomputed" to get different accuracy. 